---
dist: trusty
language: node_js
node_js: 6
sudo: false
cache:
  yarn: true
  directories:
    - node_modules
    - bower_components
    - $HOME/.cache/bower

script: ember exam --split=$SPLIT --partition=$PARTITION --filter=$FILTER --parallel=$PARALLEL

jobs:
  include:
    - stage: prepare
      before_install:
        - rm -rf node_modules
        - rm -rf bower_components
        - curl -o- -L https://yarnpkg.com/install.sh | bash
        - export PATH=$HOME/.yarn/bin:$PATH
        - yarn global add bower
        - yarn global add greenkeeper-lockfile@1
      install:
        - yarn
        - bower install
      before_script: greenkeeper-lockfile-update
      after_script: greenkeeper-lockfile-upload
      script: true
    - stage: test
      env: PARTITION=false FILTER='!acceptance' SPLIT=4 PARALLEL=true
    - stage: test
      env: PARTITION=1 FILTER='acceptance' SPLIT=4 PARALLEL=false
    - stage: test
      env: PARTITION=2 FILTER='acceptance' SPLIT=4 PARALLEL=false
    - stage: test
      env: PARTITION=3 FILTER='acceptance' SPLIT=4 PARALLEL=false
    - stage: test
      env: PARTITION=4 FILTER='acceptance' SPLIT=4 PARALLEL=false
    - stage: deploy
      script: true
      after_success:
        - test $TRAVIS_PULL_REQUEST == "false" && test $TRAVIS_BRANCH == "master" && node_modules/.bin/ember deploy staging --activate
        - test $TRAVIS_TAG && node_modules/.bin/ember deploy production --activate
      notifications:
        slack:
          secure: oloxDKdwXmNHKhh5WSR8DDxA3WJdAnyj+vj/8yawF1zG0tgL4fyPzzFqSpEhfsfgBrJlvxFtSnnsWEIMSMdT1LTwReClyjsy3PFQnHIiLMv/IZUS7ijahXQ4XL+ejfyPV4rJtFuKOLuNMww8uniy705/QkqBYwFUAcXXQ3gV5V8=
    - stage: cleanup
      after_script:
        - rm -rf node_modules
        - rm -rf bower_components
